# Generated by Django 2.2.4 on 2021-04-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='note',
            field=models.TextField(default='old_notes', max_length=1000),
            preserve_default=False,
        ),
    ]
