# Generated by Django 2.2.4 on 2021-04-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_author_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='book',
            new_name='books',
        ),
        migrations.AlterField(
            model_name='author',
            name='note',
            field=models.TextField(),
        ),
    ]
